apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:  # The selector field defines how the deployment finds which pod to manage       
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: backend
    spec:
      containers:
        - name: backend
          image: "achalise/demo-backend"
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo
    tier: backend


