apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:  # The selector field defines how the deployment finds which pod to manage       
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "achalise/demo-frontend"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: frontend
    tier: frontend
  type: ClusterIP
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fullstackapp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
spec:
  #tls:
  #- hosts:
  #  - hello-kubernetes-stg.com 
  #  secretName: example-app-tls
  rules:
  - host: fullstackapp.com  
    http:
      paths:
      - path: /api/users
        backend:
          serviceName: backend
          servicePort: 8080

